config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: {registrations: "registrations"}
  # devise_for :users, controllers: {sessions: "sessions"}
  # devise_for :users, controllers: {passwords: "passwords"}

  devise_for :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords =>       "users/passwords" }

  get 'restaurants/:restaurant_id/search', to: "products#search", as:"search"


  get 'carts/show'
  # get 'restaurants/index
  # get 'restaurants/create'
  # get 'restaurants/new'
  # get 'restaurants/edit'
  # get 'restaurants/update'
  # get 'restaurants/show'
  # get 'restaurants/destroy'
  resources :tags
  resources :taggings

  # get 'tags/:tag', to: 'restaurant_products#index', as: :tag
  resources :restaurants do

    resources :products

      # get '/tags/:tag', to: 'products#index', as: :tag
  end
  resources :line_items
  resource :carts, only:[:show, :checkout] # notice resource instead of resources
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'carts/checkout', to: 'carts#checkout', as:'checkout'
  root 'restaurants#home'


  # get '/restaurants/restaurant_id/products/tags/:id', to: 'tags#show', as:'tag_show'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @line_items = current_order.line_items
  end
  def checkout
    @line_items = current_order.line_items
    render 'carts/final_checkout'
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<%= link_to "#{current_order.line_items.size} items with a value of ₹#{current_order.subtotal}", carts_path %>

app/views/carts/_carts_item.html.erb
<h2> Cart </h2>
<% @line_items.each do |item|%>

    <h5><%= item.product.name%> </h5>
    <h5><%= item.product.price%> </h5>

    <%= form_for item, remote: true do |f|%>

        <%= f.hidden_field :product_id, :value => item.product.id %>
        <%= f.number_field :quantity, :value => item.quantity.to_i %>
        <%= f.submit "Update Cart" %>
        <%= link_to "Remove Item", line_item_path(item), method: :delete, remote: true %>

    <% end %>

    <h4>subtotal: <%= item.total %></h4>

<% end %>

<h3 style = "color:green">Your current cart value has a subtotal of: ₹ <%= current_order.subtotal %></h3>

<%= button_to "Checkout" , checkout_path %>

<%= link_to "Home", root_path %>

app/views/carts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="">
     <img src="/assets/zomato-logo-black-1.png" alt="" width="110" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      <form class="d-flex">
        <input class="form-control me-2" style = "float:right; margin-left: 5rem; padding-right: 5rem" type="search" placeholder="Enter Location" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>





        <li style = "float:right; margin-left: 2rem">
        <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= link_to current_user.name, "destroy_user_session_path", class:"text-decoration-none ", style:"color:white; "%>
          </button>
           <ul class="dropdown-menu" style="margin-left: 65rem">
    <li><a class="dropdown-item" href="#">Profile</a></li>
    <li><a class="dropdown-item" href="#">Notifications</a></li>
    <li><a class="dropdown-item" href="#">Bookmarks</a></li>
    <li><a class="dropdown-item" href="#">Reviews</a></li>
    <li><a class="dropdown-item" href="#">Network</a></li>
    <li><a class="dropdown-item" href="#">Find Friends</a></li>            
    <li><%= link_to "My Order","#" ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>


    <%# <li><a class="dropdown-item" href= "edit_user_registration_path" >Edit Profile</a></li> %>
    <li><%= link_to "Edit Profile", edit_user_registration_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
  </ul>
  </li>
      </ul>
    </div>
  </div>
</nav>

app/views/carts/final_checkout.html.erb
<br>
<h1>Order Receipt</h1>
<br>
<hr>
<br>
<h4> Name: <%= current_user.name %> </h4>
<h4> Email ID: <%= current_user.email %> </h4>
<br>
<hr>
<br>
<h4> Order Items </h4>
<br>
<%= @line_items.each do |item|%>
    <ul>
        <li><%= item.product.name%> x <%= item.quantity%> = <%= item.total%> </li>
    </ul>
<% end %>
<br>
<h2 style = "color:green">Your current cart value has a subtotal of: ₹ <%= current_order.subtotal %></h2>

app/views/carts/show.html.erb
<%= render "nav" %>

<div>
    <%= render 'carts_item' %>
    
</div>