config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: {registrations: "registrations"}
  # devise_for :users, controllers: {sessions: "sessions"}
  # devise_for :users, controllers: {passwords: "passwords"}

  devise_for :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords =>       "users/passwords" }

  get 'restaurants/:restaurant_id/search', to: "products#search", as:"search"


  get 'carts/show'
  # get 'restaurants/index
  # get 'restaurants/create'
  # get 'restaurants/new'
  # get 'restaurants/edit'
  # get 'restaurants/update'
  # get 'restaurants/show'
  # get 'restaurants/destroy'
  resources :tags
  resources :taggings

  # get 'tags/:tag', to: 'restaurant_products#index', as: :tag
  resources :restaurants do

    resources :products

      # get '/tags/:tag', to: 'products#index', as: :tag
  end
  resources :line_items
  resource :carts, only:[:show, :checkout] # notice resource instead of resources
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'carts/checkout', to: 'carts#checkout', as:'checkout'
  root 'restaurants#home'


  # get '/restaurants/restaurant_id/products/tags/:id', to: 'tags#show', as:'tag_show'

end

app/models/tag.rb
class Tag < ApplicationRecord


  has_many :taggings
  has_many :products, through: :taggings
	
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController



def index
	@restaurant = Restaurant.find(params[:restaurant_id])
	@products = @restaurant.products
	@tags = Tag.all

end

def show
	@tags = Tag.all
	# @restaurant = Restaurant.find(params[:restaurant_id])
    # @tag_products = params[:tag] ? @products.tagged_with(params[:tag]) : @products
    @tag = Tag.find(params[:id])
    @t_products = @tag.products
    # @tag_products = @t_products.where(restaurant_id: @restaurant.id)

end


end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="">
     <img src="/assets/zomato-logo-black-1.png" alt="" width="110" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>









        <li style = "float:right; margin-left: 2rem">
        <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= link_to current_user.name, "destroy_user_session_path", class:"text-decoration-none ", style:"color:white; "%>
          </button>
           <ul class="dropdown-menu" style="margin-left: 65rem">
    <li><a class="dropdown-item" href="#">Profile</a></li>
    <li><a class="dropdown-item" href="#">Notifications</a></li>
    <li><a class="dropdown-item" href="#">Bookmarks</a></li>
    <li><a class="dropdown-item" href="#">Reviews</a></li>
    <li><a class="dropdown-item" href="#">Network</a></li>
    <li><a class="dropdown-item" href="#">Find Friends</a></li>            
    <li><%= link_to "My Order","#" ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>


    <%# <li><a class="dropdown-item" href= "edit_user_registration_path" >Edit Profile</a></li> %>
    <li><%= link_to "Edit Profile", edit_user_registration_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
  </ul>
  </li>
      </ul>
    </div>
  </div>
</nav>

app/views/tags/_tag.html.erb
<li class = "tag-link" >
	<% @tags.each do |tag| %>
		<span class = "badge bg-secondary" ><%= link_to tag.name, tag %></span>
	<% end %>

</li>  

app/views/tags/index.html.erb
<%= render 'tag'%>

app/views/tags/show.html.erb
<%= render 'nav' %>


<!-- Sidebar for filters -->
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  width: 100%;
  position: static;
  z-index: 1;
  top: 100px;
  left: 1050px;
  background: #eee;
  overflow-x: hidden;
  padding: 8px 0;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
  <h3 style="text-align:center">  Filters </h3>
  <p style= "margin-left: 20px;font-size: 20px;">Filter by Tags </p><br>


<% @tags.each do |tag| %>
  &nbsp;
  <%#= tag.name %>
  <%= check_box_tag(:tag) %>
  <%= label_tag(:tag, tag.name) %>


<% end %>



</div>

<%= render 'tags/tag'%>

      <h1 style = "margin-top: 4rem;">Products</h1>

      <table>
        <thead>
          <tr>

            <th>Name</th>
            <th>Price</th>
            <th>Veg nveg</th>
            <th>Category</th>
            <th>Portion</th>
            <th>Tags</th>
            <th colspan="3"></th>
          </tr>
        </thead>


        <tbody>
          <% @t_products.each do |product| %>
            <tr>
              

              <td><%= product.name %></td>
              <td><%= product.price %></td>
              <td><%= product.veg_nveg %></td>
              <td><%= product.category %></td>
              <td><%= product.portion %></td>


<!--
              <p><small><%#= raw product.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small></p>

-->

              <td><%= link_to 'Show', restaurant_product_path(product.restaurant_id, product) %></td>
              <td><%= link_to 'Edit', edit_restaurant_product_path(product.restaurant_id, product) %>

            </tr>
          <% end %>
        </tbody>
      </table>