config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: {registrations: "registrations"}
  # devise_for :users, controllers: {sessions: "sessions"}
  # devise_for :users, controllers: {passwords: "passwords"}

  devise_for :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords =>       "users/passwords" }

  get 'restaurants/:restaurant_id/search', to: "products#search", as:"search"


  get 'carts/show'
  # get 'restaurants/index
  # get 'restaurants/create'
  # get 'restaurants/new'
  # get 'restaurants/edit'
  # get 'restaurants/update'
  # get 'restaurants/show'
  # get 'restaurants/destroy'
  resources :tags
  resources :taggings

  # get 'tags/:tag', to: 'restaurant_products#index', as: :tag
  resources :restaurants do

    resources :products

      # get '/tags/:tag', to: 'products#index', as: :tag
  end
  resources :line_items
  resource :carts, only:[:show, :checkout] # notice resource instead of resources
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'carts/checkout', to: 'carts#checkout', as:'checkout'
  root 'restaurants#home'


  # get '/restaurants/restaurant_id/products/tags/:id', to: 'tags#show', as:'tag_show'

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

    has_many :products
    belongs_to :user
    has_many :reviews
    # has_one_attached :image

    mount_uploader :image, ImageUploader
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    # @products = Product.all
    # @line_item = current_order.line_items.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # @product = Product.find(params[:id])
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    #
    redirect_to root_path

    # respond_to do |format|
    #   format.html { redirect_to restaurants_path(restaurant) }
    #   format.json { head :no_content }
    #   format.js   { render :layout => false }
    # end

  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :cuisine, :open_time, :close_time, :location, :user_id, :image)
  end


end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant, id: "new_restaurant" do |form| %>

  <div>
  <%= form.label :restaurant_image %><br>
  <%= form.file_field :image %>
  </div>


  <div>
    <%= form.label :restaurant_name %><br>
    <%= form.text_field :name %>
    <% restaurant.errors.full_messages_for(:res_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :cuisine %><br>
    <%= form.text_area :cuisine %><br>
    <% restaurant.errors.full_messages_for(:cuisine).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.label :open_time %><br>
    <%= form.text_area :open_time %><br>
    <% restaurant.errors.full_messages_for(:open_time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :close_time %><br>
    <%= form.text_area :close_time %><br>
    <% restaurant.errors.full_messages_for(:close_time).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_area :location %><br>
    <% restaurant.errors.full_messages_for(:location_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>



  <div>
    <%# <%= form.label :Manager %>
    <%= form.hidden_field :user_id , value: current_user.id%><br>
    <% restaurant.errors.full_messages_for(:manager_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>

  <%= link_to "Home", root_path%>
<% end %>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
<script type="text/javascript">
  <%= render "validate.js" %>
</script>

app/views/restaurants/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="">
     <img src="/assets/zomato-logo-black-1.png" alt="" width="110" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>

          <a class="nav-link"><%= link_to "Order Online", restaurants_path%></a>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      <form class="d-flex">
        <input class="form-control me-2" style = "float:right; margin-left: 5rem; padding-right: 5rem" type="search" placeholder="Enter Location" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>





        <li style = "float:right; margin-left: 2rem">
        <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= link_to current_user.name, "destroy_user_session_path", class:"text-decoration-none ", style:"color:white; "%>
          </button>
           <ul class="dropdown-menu" style="margin-left: 65rem">
    <li><a class="dropdown-item" href="#">Profile</a></li>
    <li><a class="dropdown-item" href="#">Notifications</a></li>
    <li><a class="dropdown-item" href="#">Bookmarks</a></li>
    <li><a class="dropdown-item" href="#">Reviews</a></li>
    <li><a class="dropdown-item" href="#">Network</a></li>
    <li><a class="dropdown-item" href="#">Find Friends</a></li>            
    <li><%= link_to "My Order","#" ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>


    <%# <li><a class="dropdown-item" href= "edit_user_registration_path" >Edit Profile</a></li> %>
    <li><%= link_to "Edit Profile", edit_user_registration_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
  </ul>
  </li>
      </ul>
    </div>
  </div>
</nav>

app/views/restaurants/_validate.js.erb
$("#new_restaurant").validate({

//adding rule
  rules: {
  // username is required with max of 20 and min of 6
  "restaurant[name]":{
    required: true,
    maxlength: 20,
    minlength: 6
  },


  // username is required with max of 20 and min of 6
  "restaurant[cuisine]":{
    required: true,
    maxlength: 20,
    minlength: 6
  },

    // username is required with max of 20 and min of 6
  "restaurant[open_time]":{
    required: true
  },

    // username is required with max of 20 and min of 6
  "restaurant[close_time]":{
    required: true
  },

    // username is required with max of 20 and min of 6
  "restaurant[location]":{
    required: true,
    minlength: 2
  }

  },
 
  messages: {
    name:{
      required: "Restaurant name is required.",
      maxlength: "Restaurant name must be less than 20",
      minlength: "Restaurant name must be more than 6"
    },

    cuisine:{
      required: "Restaurant name is required.",
      maxlength: "Restaurant name must be less than 20",
      minlength: "Restaurant name must be more than 6"
    },


        open_time:{
      required: "Restaurant name is required.",
    },

        close_time:{
      required: "Restaurant name is required.",
      maxlength: "Restaurant name must be less than 20",
      minlength: "Restaurant name must be more than 6"
    },


        location:{
      required: "Restaurant name is required.",
      minlength: "Restaurant name must be more than 6"
    }
  }
});

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/destroy.js.erb
$('.delete_restaurant').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/home.html.erb
<%= render "nav" %>
<div class = 'zomato_poster' >

  <h1 style = "margin-top: 5rem; text-align:center; font-style: italic; font-size: 80px; color:rgb(255, 255, 255);">zomato </h1>
  <p style = "font-family: arial; text-align:center; font-size: 30px; color:rgb(255, 255, 255);">Discover the best food & drinks in your city</p>

  <div style = 'color: white'>
    <%= form_tag(restaurants_path)  do %>
      <div class = "search_box" >Store <br><%= text_field_tag :res_name %>
      <%= submit_tag 'Search' %> <br>


    </div>
    <% end %>
  </div>

</div>
<div class = 'order_button'>
  <%= link_to "Order Online", restaurants_path %>
</div>
<br>

app/views/restaurants/index.html.erb
<%= stylesheet_link_tag "restaurants"%>


<% if user_signed_in? %>

<%= render "nav" %>

  <%# if user is manager %>
  <% if current_user.user_role == "manager" %>
    <h1 style="text-align:center"></h1>
    <% if @restaurants.size == 0 %>
      <h3 style="color:red">No restaurants added yet. Add One !</h3>
      Add new restaurant by clicking <%= link_to "here", new_restaurant_path, style:"text-decoration:none" %>
      <% else %>
    
        <script src="https://kit.fontawesome.com/cac2174d5a.js" crossorigin="anonymous"></script>
        <div style = 'font-size:48px;color:maroon'>
          <h2 style = "text-align:center; font-size: 50px"> Your Restaurants <i class="fas fa-store"></i></h2>
        </div>

        <ul style = 'font-size: 20px;'>
          <% @restaurants.each do |restaurant| %>

            <!--
              <%= link_to restaurant.name, restaurant %>
            -->
            <% if restaurant.user_id == current_user.id %>


            



              <div style = 'align: center; background-color: #ffc0cb; /* Green */
                border: none;
                color: white;
                padding: 20px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
                border-radius: 12px;'>


<%= link_to(image_tag(restaurant.image.thumb.url, alt: 'Image'), restaurant) if restaurant.image? %><br><br>
                <%= link_to restaurant.name, restaurant, :method => "get" %>
              </div>
              <br>
              </a>
              <br>
            <%end%>

            <%= link_to "Edit", edit_restaurant_path(restaurant) %> |<%= link_to "Destroy", restaurant_path(restaurant),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
             <br>
             <hr>
             <br>
          <% end %>
        </ul>
        <p style = "text-align:center; font-size: 50px">Add new Restaurant by clicking <%= link_to "here", new_restaurant_path, style:"text-decoration:none"%> <br></p>
        <%= button_to "Home", root_path, :method => "get" %>
        <br>
      <% end %>


    <%# if user is customer %>
    <% elsif current_user.user_role == "customer" %> 

      <% if @restaurants.size == 0 %>
        <h3 style="color:red">No restaurants added yet. </h3>

        <% else %>

          <script src="https://kit.fontawesome.com/cac2174d5a.js" crossorigin="anonymous"></script>
          <div style = 'font-size:48px;color:maroon'>
            <h2 style = "text-align:center; font-size: 50px"> Fast Delivery <i class="fas fa-motorcycle"></i></h2>
          </div>    


            <% @restaurants.each do |restaurant| %>
              <!--
                <%= link_to restaurant.name, restaurant %>
              -->
              <div style = 'align: center; background-color: #ffc0cb; /* Green */
                border: none;
                color: white;
                padding: 20px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
                border-radius: 12px;'>

                <%= link_to(image_tag(restaurant.image.thumb.url, alt: 'Image'), restaurant ,target: '_blank') if restaurant.image? %><br><br>

                <%= link_to restaurant.name, restaurant, :method => "get" %>
                <br>
                </a>
                <br>
              </div>
            <% end %>
          <%= button_to "Home", root_path, :method => "get" %>
          <br>
        <% end %>
    <% end %>
<%end%>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>



<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<% if user_signed_in? %>
<%= render "nav" %>

    <%# if user is manager %>
    <% if current_user.user_role.downcase == "manager" %>

        <h1><%= @restaurant.name %></h1>

        <h2>Cuisine: </h2><%= @restaurant.cuisine %>
        <h2> Opening Time: </h2><%= @restaurant.open_time.strftime("%H:%M") %>
        <h2>Closing Time: </h2><%= @restaurant.close_time.strftime("%H:%M") %>
        <h2>Location: </h2><%= @restaurant.location %>
        <br>
        <br>
        <%= link_to "Products", restaurant_products_path(@restaurant) %>
        <hr>
        <%= link_to "Edit", edit_restaurant_path(@restaurant) %> | 
        <%= link_to "Destroy", restaurant_path(@restaurant),
        method: :delete,
        data: { confirm: "Are you sure?" } %> |
        <%= link_to "Back to Restaurants", restaurants_path %> | 
        <%= link_to "Home", root_path%>
        <hr>
    
        <% elsif current_user.user_role.downcase == "customer"  %>
            <h1><%= @restaurant.name %></h1>
            <h2>Cuisine: </h2><%= @restaurant.cuisine %>
            <h2> Opening Time: </h2><%= @restaurant.open_time.strftime("%H:%M") %>
            <h2>Closing Time: </h2><%= @restaurant.close_time.strftime("%H:%M") %>
            <h2>Location: </h2><%= @restaurant.location %>
            <br>
            <br>
            <%= link_to "Order Online", restaurant_products_path(@restaurant) %> |
            <hr>
            <%= link_to "Back to Restaurants", restaurants_path %> | 
            <%= link_to "Home", root_path%>
            <hr>
    <% end %> 
<% end %>   

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>