config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # devise_for :users, controllers: {registrations: "registrations"}
  # devise_for :users, controllers: {sessions: "sessions"}
  # devise_for :users, controllers: {passwords: "passwords"}

  devise_for :controllers => { :registrations => "users/registrations", :sessions => "users/sessions", :passwords =>       "users/passwords" }

  get 'restaurants/:restaurant_id/search', to: "products#search", as:"search"


  get 'carts/show'
  # get 'restaurants/index
  # get 'restaurants/create'
  # get 'restaurants/new'
  # get 'restaurants/edit'
  # get 'restaurants/update'
  # get 'restaurants/show'
  # get 'restaurants/destroy'
  resources :tags
  resources :taggings

  # get 'tags/:tag', to: 'restaurant_products#index', as: :tag
  resources :restaurants do

    resources :products

      # get '/tags/:tag', to: 'products#index', as: :tag
  end
  resources :line_items
  resource :carts, only:[:show, :checkout] # notice resource instead of resources
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'carts/checkout', to: 'carts#checkout', as:'checkout'
  root 'restaurants#home'


  # get '/restaurants/restaurant_id/products/tags/:id', to: 'tags#show', as:'tag_show'

end

app/models/product.rb
class Product < ApplicationRecord

    has_many :line_items
    belongs_to :restaurant
    mount_uploader :image, ImageUploader

    attr_accessor :terms_accepted, :image
    # has_one_attached :image

    has_many :taggings
    has_many :tags, through: :taggings

    def self.tagged_with(name)
        Tag.find_by!(name: name).products
    end

    def self.tag_counts
        Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
    end

    def tag_list
        tags.map(&:name).join(', ')
    end

    def tag_list=(names)
        self.tags = names.split(',').map do |n|
        Tag.where(name: n.strip).first_or_create!
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @products = @restaurant.products


    @tag_products = params[:tag] ? @products.tagged_with(params[:tag]) : @products
    @tags = Tag.all
    

    @line_item = current_order.line_items.new
  end

  # GET /products/1 or /products/1.json
  def show
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  # GET /products/new
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.new
  end

  # GET /products/1/edit
  def edit
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
  end

  # POST /products or /products.json
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.create(product_params)

      if @product.save
          redirect_to restaurant_path(@restaurant)
      else
        render :new
      end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
      if @product.update(product_params)
        redirect_to restaurant_product_path
      else  
        render :edit
      end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @product = @restaurant.products.find(params[:id])
    # @product = Product.find(params[:id])
    @product.destroy
    # @products = @restaurant.products
    # redirect_to restaurant_path(@restaurant)

    respond_to do |format|
      format.html { redirect_to restaurant_products_path(restaurant) }
      format.json { head :no_content }
      format.js   { render :layout => false }
    end
  end



  def search
    @restaurant = Restaurant.find(params[:restaurant_id])
    @products = @restaurant.products
    @line_item = current_order.line_items.new

    if params[:search].blank?
      redirect_to restaurant_products_path and return
    else
      @parameter = params[:search].downcase
      @results = @products.where("lower(name) LIKE :search", search: "%#{@parameter}%")
    end

  end


def product_search
     @restaurant = Restaurant.find(params[:restaurant_id])
    @products = @restaurant.products
    @line_item = current_order.line_items.new

    if params[:productsearch].blank?
      redirect_to restaurant_products_path and return
    else
      @parameter = params[:productsearch].downcase
      @results = @products.where("lower(tags) LIKE :productsearch", productsearch: "%#{@parameter}%")
    end

end


  private
    def set_product
      @restaurant = Restaurant.find(params[:restaurant_id])
      @product = @restaurant.products.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :veg_nveg, :category, :portion, :restaurant_id, :search, :image, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for @product, url: restaurant_products_path do |f| %>
  <%= f.input :name %><br>
  <%= f.input :price %><br>
  <%= f.input :veg_nveg, label: 'Veg or Non Veg ' %><br>
  <%= f.input :category %><br>
  <%= f.input :portion %><br>
  <%= f.input :tag_ids, label: 'Add Tags', as: :select, collection: Tag.order(:name), label_method: :name, input_html: {class: 'form-control select 2', multiple: true} %>



  <%= f.submit "Submit", class: 'btn btn-lg btn-primary float-right' %>


  <%#= f.button :submit %>
<% end %>

<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script> -->
<!-- <script type="text/javascript"> -->
   <%#= render "product-validate.js" %>
<!-- </script> -->

app/views/products/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="">
     <img src="/assets/zomato-logo-black-1.png" alt="" width="110" height="24">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>



    <%= form_tag(search_path(@restaurant), :method => "get") do %>
    <div class= "input-group" style = "float:right; margin-left: 10rem; padding-right: 4rem">
      <%= search_field_tag :search, params[:search], placeholder: "Search for Products", class: "form-control" %>
      <div class = "input-group-btn">
        <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>

      </div>
    </div>
    <% end %>





        <li style = "float:right; margin-left: 2rem">
        <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= link_to current_user.name, "destroy_user_session_path", class:"text-decoration-none ", style:"color:white; "%>
          </button>
           <ul class="dropdown-menu" style="margin-left: 65rem">
    <li><a class="dropdown-item" href="#">Profile</a></li>
    <li><a class="dropdown-item" href="#">Notifications</a></li>
    <li><a class="dropdown-item" href="#">Bookmarks</a></li>
    <li><a class="dropdown-item" href="#">Reviews</a></li>
    <li><a class="dropdown-item" href="#">Network</a></li>
    <li><a class="dropdown-item" href="#">Find Friends</a></li>            
    <li><%= link_to "My Order","#" ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>


    <%# <li><a class="dropdown-item" href= "edit_user_registration_path" >Edit Profile</a></li> %>
    <li><%= link_to "Edit Profile", edit_user_registration_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
  </ul>
  </li>
      </ul>
    </div>
  </div>
</nav>

app/views/products/_product-validate.js.erb
$("#new_product").validate({

//adding rule
  rules: {
  // name is required with max of 20 and min of 2
  "product[name]":{
    required: true,
    maxlength: 20,
    minlength: 2
  },


  // price is required with min value of 0
  "product[price]":{
    required: true,
    min: 0
  },

    // veg_nveg is required
  "product[veg_nveg]":{
    required: true
  },

    // category is required
  "product[category]":{
    required: true
  },

    // portion is required
  "product[portion]":{
    required: true
  }

  },
 
  messages: {
    name:{
      required: "Product name is required.",
      maxlength: "Product name must be less than 20",
      minlength: "Product name must be more than 2"
    },

    price:{
      required: "Product cost is required.",
      minlength: "Product cost must be more than 0"
    },


        veg_nveg:{
      required: "Answer is required.",
    },

        category:{
      required: "Product category is required."
    },


        portion:{
      required: "Product portion is required."
    }
  }
});

app/views/products/_tag.html.erb
<%= simple_form_for @products, url: restaurant_products_path do |f| %>

  <%= f.input :tag_ids, label: 'Add Tags', as: :select, collection: @tags.order(:name), label_method: :name, input_html: {multiple: true} %>
  <%= f.submit "Submit", class: 'btn btn-lg btn-primary float-right' %>


  <%= f.button :submit %>
<% end %>

app/views/products/_validate.js.erb
$("#new_product").validate({

//adding rule
  rules: {
  // name is required with max of 20 and min of 6
  "product[name]":{
    required: true,
    maxlength: 20,
    minlength: 2
  },


  // price is required with max of 20 and min of 6
  "product[price]":{
    required: true,
    min: 0
  },

    // veg_nveg is required with max of 20 and min of 6
  "product[veg_nveg]":{
    required: true
  },

    // category is required with max of 20 and min of 6
  "product[category]":{
    required: true
  },

    // portion is required with max of 20 and min of 6
  "product[portion]":{
    required: true
  }

  },
 
  messages: {
    name:{
      required: "Product name is required.",
      maxlength: "Product name must be less than 20",
      minlength: "Product name must be more than 2"
    },

    price:{
      required: "Product cost is required.",
      minlength: "Product cost must be more than 0"
    },


        veg_nveg:{
      required: "Answer is required.",
    },

        category:{
      required: "Product category is required."
    },


        portion:{
      required: "Product portion is required."
    }
  }
});

app/views/products/destroy.js.erb
$('.delete_product').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>


<%= link_to 'Back', restaurant_products_path %> | 
<%= link_to "Home", root_path%>

app/views/products/index.html.erb
<%= render "nav" %>
<!-- -->
<% if user_signed_in? %>
  <% if current_user.user_role.downcase == "manager" %>
    <%if @tag_products.size == 0%>
      <h2> No Products Added Yet. Add Some ! 
      <%= link_to "Add", new_restaurant_product_path %></h2>
    <%else%>


<!-- Sidebar for filters -->
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  width: 100%;
  position: static;
  z-index: 1;
  top: 100px;
  left: 1050px;
  background: #eee;
  overflow-x: hidden;
  padding: 8px 0;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
  <h3 style="text-align:center">  Filters </h3>
  <p style= "margin-left: 20px;font-size: 20px;">Filter by Tags </p><br>
      <%= form_tag(search_path(@restaurant), :method => "get") do %>
    <div class= "input-group" style = "float:right; width: 300px;margin-left: 5rem; padding-right: 2rem">
      <%= search_field_tag :search, params[:search], placeholder: "Enter tags", class: "form-control" %>
      <div class = "input-group-btn">
        <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
      </div>
    </div>
    <% end %>
<!--   <a href="#about">About</a>
  <a href="#services">Services</a>
  <a href="#clients">Clients</a>
  <a href="#contact">Contact</a> -->

<!-- to enter the list of tags with clickable filters -->
<%#= render "tag" %>
<% @tags.each do |tag| %>
  &nbsp;
  <%#= tag.name %>
  <%= check_box_tag(:tag) %>
  <%= label_tag(:tag, tag.name) %>


<% end %>

</div>




<%= render 'tags/tag'%>

<%= link_to 'Reset All Filters', restaurant_products_path %>

<div class="main">

  
</div>
   
</body>
</html> 




      <p id="notice"><%= notice %></p>

      <h1 style = "margin-top: 4rem;">Products</h1>

      <table>
        <thead>
          <tr>

            <th>Name</th>
            <th>Price</th>
            <th>Veg nveg</th>
            <th>Category</th>
            <th>Portion</th>
            <th>Tags</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @tag_products.each do |product| %>
            <tr>
              

              <td><%= product.name %></td>
              <td><%= product.price %></td>
              <td><%= product.veg_nveg %></td>
              <td><%= product.category %></td>
              <td><%= product.portion %></td>


<!--
              <p><small><%#= raw product.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small></p>

-->

              <td><%= link_to 'Show', restaurant_product_path(product.restaurant_id, product) %></td>
              <td><%= link_to 'Edit', edit_restaurant_product_path(product.restaurant_id, product) %>
              <td><%= link_to 'Delete', restaurant_products_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_product' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'Add Product', new_restaurant_product_path %> | 
      <%= link_to 'Back to Restaurants', restaurants_path %>
    <% end %>
  <% elsif current_user.user_role.downcase == "customer" %>
    <%if @products.size == 0%>
      <h2> No Products Added Yet.
    <%else%>

      <p id="notice"><%= notice %></p>

      <h1 style = "margin-top: 4rem;">Products</h1>

      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Veg nveg</th>
            <th>Category</th>
            <th>Portion</th>

            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= link_to(image_tag(product.image.thumb.url, alt: 'Image'), restaurant_product ,target: '_blank') if product.image? %></td>
              <td><%= product.name %></td>
              <td><%= product.price %></td>
              <td><%= product.veg_nveg %></td>
              <td><%= product.category %></td>
              <td><%= product.portion %></td>

              <td><%= link_to 'Show', restaurant_product_path(product.restaurant_id, product) %></td>
              <td>
                <%= form_for @line_item, remote: true do |f|%>
                <%= f.hidden_field :product_id, :value => product.id %>
                <%= f.number_field :quantity, :value => 1, :min => 1 %>
                <%= f.submit "Add to Cart" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <div id = "cart">
        <%= render 'carts/cart' %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= render "nav" %>


<h1>New Product</h1>

<%= render 'form', product: @product %>



<%# <%= link_to 'Back', products_path %> %>

app/views/products/search.html.erb
<%= render "nav" %>


<% if user_signed_in? %>
  <% if current_user.user_role.downcase == "manager" %>
    <%if @products.size == 0%>
      <h2> No Products Added Yet. Add Some ! 
      <%= link_to "Add", new_restaurant_product_path %></h2>
    <%else%>



<!-- Sidebar for filters -->
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidenav {
  width: 250px;
  position: fixed;
  z-index: 1;
  top: 100px;
  left: 1050px;
  background: #eee;
  overflow-x: hidden;
  padding: 8px 0;
}

.sidenav a {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 20px;
  color: #818181;
  display: block;
}

.sidenav a:hover {
  color: #f1f1f1;
}

.main {
  margin-left: 160px; /* Same as the width of the sidenav */
  font-size: 28px; /* Increased text to enable scrolling */
  padding: 0px 10px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
  <h3>  Filters </h3>
  Enter Tags <br>
      <%= form_tag(search_path(@restaurant), :method => "get") do %>
    <div class= "input-group" style = "float:right; margin-left: 5rem; padding-right: 2rem">
      <%= search_field_tag :search, params[:search], placeholder: "Enter tags", class: "form-control" %>
      <div class = "input-group-btn">
        <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>

      </div>
    </div>
    <% end %>
<!--   <a href="#about">About</a>
  <a href="#services">Services</a>
  <a href="#clients">Clients</a>
  <a href="#contact">Contact</a> -->
</div>

<div class="main">

  
</div>
   
</body>
</html> 





      <p id="notice"><%= notice %></p>

<h1 style = "margin-top: 4rem;"> Products </h1>



      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Veg nveg</th>
            <th>Category</th>
            <th>Portion</th>

            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @results.each do |result| %>
            <tr>
              <td><%= result.name %></td>
              <td><%= result.price %></td>
              <td><%= result.veg_nveg %></td>
              <td><%= result.category %></td>
              <td><%= result.portion %></td>
              <td><%= link_to 'Show', restaurant_product_path(result.restaurant_id, result) %></td>
              <td><%= link_to 'Edit', edit_restaurant_product_path(result.restaurant_id, result) %>
              <td><%= link_to 'Delete', restaurant_products_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true, :class => 'delete_product' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= link_to 'Add Product', new_restaurant_product_path %> | 
      <%= link_to 'Back to Restaurants', restaurants_path %>
    <% end %>

      <% elsif current_user.user_role.downcase == "customer" %>
    <%if @products.size == 0%>
      <h2> No Products Added Yet.
    <%else%>

      <p id="notice"><%= notice %></p>


<h1 style = "margin-top: 4rem;"> Products </h1>



      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Veg nveg</th>
            <th>Category</th>
            <th>Portion</th>

            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @results.each do |result| %>
            <tr>
              <td><%= result.name %></td>
              <td><%= result.price %></td>
              <td><%= result.veg_nveg %></td>
              <td><%= result.category %></td>
              <td><%= result.portion %></td>

              <td><%= link_to 'Show', restaurant_product_path(result.restaurant_id, result) %></td>
              <td>
                <%= form_for @line_item, remote: true do |f|%>
                <%= f.hidden_field :product_id, :value => result.id %>
                <%= f.number_field :quantity, :value => 1, :min => 1 %>
                <%= f.submit "Add to Cart" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
            <br>
      <div id = "cart">
        <%= render 'carts/cart' %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/products/show.html.erb
<%= render "nav" %>



<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Veg nveg:</strong>
  <%= @product.veg_nveg %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Portion:</strong>
  <%= @product.portion %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @product.restaurant_id %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @product.tags %>
</p>

<%# <%= link_to 'Edit', edit_restaurant_product_path %>
<%= link_to 'Back', restaurant_products_path %>

<!--

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Veg nveg:</strong>
  <%= @product.veg_nveg %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Portion:</strong>
  <%= @product.portion %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @product.restaurant_id %>
</p>

<%= link_to 'Back', root_path %>
-->